version: '3'

services:
    app:
        build: .
        entrypoint: .Docker/entrypoint.sh
        container_name: prismaapi-app
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/app
        depends_on:
            - db

    db:
        build: .Docker/postgres
        container_name: prismaapi-db
        restart: always
        tty: true
        ports:
            - "5432:5432"
        volumes:
            - .docker/dbdata:/var/lib/postgresql/dbdata
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTRES_DB=prismaapi
